---
# roles/flask-app-deployment/tasks/main.yml
# roles/flask-app-deployment/tasks/main.yml

- name: Create Python virtual environment
  command: python3 -m venv /opt/rtshark-app/venv
  args:
    creates: /opt/rtshark-app/venv

- name: Install Python dependencies in the virtual environment
  pip:
    name:
      - flask
      - flask_login
      - ansi2html
      - gunicorn
    virtualenv: /opt/rtshark-app/venv
    virtualenv_command: python3 -m venv

- name: Ensure rtshark owns the virtual environment
  file:
    path: /opt/rtshark-app/venv
    state: directory
    owner: rtshark
    group: rtshark
    recurse: yes

- name: Ensure the Flask templates directory exists
  ansible.builtin.file:
    path: /opt/rtshark-app/templates/
    state: directory
    owner: rtshark
    group: rtshark
    mode: '0755'

- name: Ensure the Flask config directory exists
  ansible.builtin.file:
    path: /opt/rtshark-app/.config/
    state: directory
    owner: rtshark
    group: rtshark
    mode: '0755'


- name: Copy Flask application files
  copy:
    src: "{{ item }}"
    dest: /opt/rtshark-app/
    owner: rtshark
    group: rtshark
  with_fileglob:
    - files/*  # Copies app.py and models.py


- name: Copy Flask template files
  copy:
    src: "{{ item }}"
    dest: /opt/rtshark-app/templates/
    owner: rtshark
    group: rtshark
    mode: '0644'
  with_fileglob:
    - templates/*  # Copies app.py and models.py

- name: Copy Flask config files
  copy:
    src: "{{ item }}"
    dest: /opt/rtshark-app/.config/
    owner: rtshark
    group: rtshark
    mode: '0644'
  with_fileglob:
    - config/*  # Copies app.py and models.py