- name: Set timezone to America/New_York
  ansible.builtin.timezone:
    name: America/New_York

- name: Update apt repo
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Optionally, update the cache if it's older than an hour

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist

- name: Install OS dependencies
  apt:
    name:
      - supervisor
      - python3
      - python3-venv
      - python3-pip
      - tshark
      - nginx
      - avahi-daemon
    state: present

- name: Ensure rtshark-app log directory exists
  ansible.builtin.file:
    path: /var/log/rtshark-app
    state: directory
    owner: rtshark
    group: rtshark
    mode: '0755'

- name: Ensure rtshark-app error log file exists
  ansible.builtin.file:
    path: /var/log/rtshark-app/rtshark-app.err.log
    state: touch
    owner: rtshark
    group: rtshark
    mode: '0644'

- name: Ensure rtshark-app output log file exists
  ansible.builtin.file:
    path: /var/log/rtshark-app/rtshark-app.out.log
    state: touch
    owner: rtshark
    group: rtshark
    mode: '0644'

- name: Ensure rtshark-app in app log file exists
  ansible.builtin.file:
    path: /var/log/rtshark-app/inapplog.log
    state: touch
    owner: rtshark
    group: rtshark
    mode: '0644'

- name: Ensure cryptography is installed
  ansible.builtin.pip:
    name: cryptography
    state: present

- name: Allow non-superusers to capture packets
  ansible.builtin.debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: true
    vtype: boolean

- name: Apply the Wireshark configuration
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive wireshark-common
  become: true

- name: Create captures directory
  ansible.builtin.file:
    path: /captures
    state: directory
    owner: tsharkuser
    group: tsharkuser
    mode: '0755'

- name: Set capabilities on TShark binary
  ansible.builtin.command:
    cmd: setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/tshark
  args:
    creates: "/usr/bin/tshark"

- name: Change group ownership and set permissions for 'dumpcap'
  ansible.builtin.file:
    path: /usr/bin/dumpcap
    group: wireshark
    mode: '0750'