- name: Create user rtshark
  user:
    name: rtshark
    system: yes
    home: /opt/rtshark-app
    shell: /sbin/nologin

- name: Set permissions for /opt/rtshark-app
  file:
    path: /opt/rtshark-app
    owner: rtshark
    group: rtshark
    recurse: yes

- name: Grant sudo rights to rtshark
  lineinfile:
    path: /etc/sudoers
    line: 'rtshark ALL=(ALL) NOPASSWD: /bin/systemctl start tshark.service, /bin/systemctl stop tshark.service, /bin/systemctl status tshark.service --no-pager'
    validate: '/usr/sbin/visudo -cf %s'

# tasks file for tshark-setup

- name: Create dedicated user for TShark
  ansible.builtin.user:
    name: tsharkuser
    system: yes
    create_home: no

- name: Create 'wireshark' group if it doesn't exist
  ansible.builtin.group:
    name: wireshark
    state: present

- name: Add 'tsharkuser' to 'wireshark' group
  ansible.builtin.user:
    name: tsharkuser
    groups: wireshark
    append: yes

