---
# playbooks/main.yml

- hosts: all
  become: yes
  roles:
    - environment-setup
    - supervisor-setup
    - flask-app-deployment
    - service-setup
    - scripts-setup
    - user-setup
    - app-maintenance
    - nginx-setup
    - app-maintenance
    - supervisor-setup
    - network-setup
    # ... other roles
