# playbooks/main.yml
- hosts: all
  pre_tasks:
    - name: Include secrets
      include_vars:
        file: ../secrets.yml
        name: secrets
  become: yes
  roles:
    # - environment-setup
    # - user-setup
    - flask-app-deployment
    # - scripts-setup
    # - service-setup
    # - nginx-setup
    # - app-maintenance
    # - supervisor-setup
    # - network-setup
    # ... other roles
