- name: Generate OpenSSL Private Key
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/nginx-selfsigned.key
    type: RSA
    size: 4096  # You can choose the key size

- name: Generate a Self-Signed OpenSSL Certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/certs/nginx-selfsigned.crt
    privatekey_path: /etc/ssl/private/nginx-selfsigned.key
    provider: selfsigned


- name: Deploy Nginx configuration
  template:
    src: files/default.conf
    dest: /etc/nginx/sites-available/default

- name: Deploy Nginx configuration
  template:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
